from app.graph.state import BusinessState
from app.llm.groq_client import llm


def _ask(prompt: str) -> str:
    return llm.invoke(prompt).content


def research_node(state: BusinessState):

    company = state["company"]

    prompt = f"""
You are a senior business research analyst.

Prepare a detailed company overview for {company}.

Include:

- Company Overview
- Business Model
- Products & Services
- Industry
- Recent Developments
"""

    state["research"] = _ask(prompt)

    return state


def market_node(state: BusinessState):

    company = state["company"]

    prompt = f"""
Perform a market analysis for {company}.

Include:

- Industry Size
- Growth
- Market Trends
- Opportunities
- Threats
"""

    state["market_analysis"] = _ask(prompt)

    return state


def competitor_node(state: BusinessState):

    company = state["company"]

    prompt = f"""
Perform a competitor analysis for {company}.

Include:

- Main Competitors
- Competitive Advantages
- Market Position
- Comparison Table
"""

    state["competitor_analysis"] = _ask(prompt)

    return state


def swot_node(state: BusinessState):

    company = state["company"]

    prompt = f"""
Create a SWOT Analysis for {company}.

Include:

- Strengths
- Weaknesses
- Opportunities
- Threats
"""

    state["swot"] = _ask(prompt)

    return state


def pestle_node(state: BusinessState):

    company = state["company"]

    prompt = f"""
Perform a PESTLE Analysis for {company}.

Include:

- Political
- Economic
- Social
- Technological
- Legal
- Environmental
"""

    state["pestle"] = _ask(prompt)

    return state


def porter_node(state: BusinessState):

    company = state["company"]

    prompt = f"""
Perform Porter's Five Forces Analysis for {company}.

Include:

- Threat of New Entrants
- Bargaining Power of Suppliers
- Bargaining Power of Buyers
- Threat of Substitutes
- Competitive Rivalry
"""

    state["porter"] = _ask(prompt)

    return state


def finance_node(state: BusinessState):

    company = state["company"]

    prompt = f"""
Perform a financial analysis for {company}.

Include:

- Revenue
- Profitability
- Growth
- Financial Risks
- Key KPIs
"""

    state["financial"] = _ask(prompt)

    return state


def strategy_node(state: BusinessState):

    company = state["company"]

    prompt = f"""
Generate strategic recommendations for {company}.

Include:

- Short-term Strategy
- Long-term Strategy
- Growth Strategy
- Innovation Strategy
- Risk Mitigation
"""

    state["strategy"] = _ask(prompt)

    return state


def executive_node(state: BusinessState):

    company = state["company"]
    report_type = state["report_type"]

    state["final_report"] = f"""
# {company}

## {report_type}

---

# Executive Summary

{state["research"][:1200]}

---

# Company Research

{state["research"]}

---

# Market Analysis

{state["market_analysis"]}

---

# Competitor Analysis

{state["competitor_analysis"]}

---

# SWOT Analysis

{state["swot"]}

---

# PESTLE Analysis

{state["pestle"]}

---

# Porter's Five Forces

{state["porter"]}

---

# Financial Analysis

{state["financial"]}

---

# Strategic Recommendations

{state["strategy"]}

---

Generated by

AI Business Strategy Consultant

Powered by LangGraph • Groq • Llama 3.3
"""

    return state
